# Generated by Django 3.2.4 on 2021-08-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20210815_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(default='', upload_to='uploads/images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='notice',
            name='image',
        ),
    ]
