# Generated by Django 3.2.4 on 2021-08-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='image',
            field=models.ImageField(default='', upload_to='uploads/images/'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='pdf',
            field=models.FileField(default='', upload_to='uploads/notices/'),
        ),
    ]
